{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  Running command git clone --filter=blob:none --quiet https://github.com/arendjan/tmx-pico-aio.git 'C:\\Users\\arendjanvanhil\\AppData\\Local\\Temp\\pip-req-build-o0q40nu9'\n",
      "  Running command git checkout -b sensors --track origin/sensors\n",
      "  branch 'sensors' set up to track 'origin/sensors'.\n",
      "  Switched to a new branch 'sensors'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting git+https://github.com/arendjan/tmx-pico-aio.git@sensors\n",
      "  Cloning https://github.com/arendjan/tmx-pico-aio.git (to revision sensors) to c:\\users\\arendjanvanhil\\appdata\\local\\temp\\pip-req-build-o0q40nu9\n",
      "  Resolved https://github.com/arendjan/tmx-pico-aio.git to commit 2459ee30acf0ffd3237aefe703b82a64a5805dd9\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'done'\n",
      "  Preparing metadata (pyproject.toml): started\n",
      "  Preparing metadata (pyproject.toml): finished with status 'done'\n",
      "Collecting pyserial (from tmx-pico-aio==1.3)\n",
      "  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)\n",
      "Collecting aioserial (from tmx-pico-aio==1.3)\n",
      "  Using cached aioserial-1.3.1-py3-none-any.whl\n",
      "Building wheels for collected packages: tmx-pico-aio\n",
      "  Building wheel for tmx-pico-aio (pyproject.toml): started\n",
      "  Building wheel for tmx-pico-aio (pyproject.toml): finished with status 'done'\n",
      "  Created wheel for tmx-pico-aio: filename=tmx_pico_aio-1.3-py3-none-any.whl size=32784 sha256=74668a05955015f94b9251c1969d71621449a66eb37bed2bbbad57af236d9269\n",
      "  Stored in directory: C:\\Users\\arendjanvanhil\\AppData\\Local\\Temp\\pip-ephem-wheel-cache-oayf713l\\wheels\\1c\\4f\\5c\\a235d1789f13b2c95cbcba16067f910096d51385f2043ef27e\n",
      "Successfully built tmx-pico-aio\n",
      "Installing collected packages: pyserial, aioserial, tmx-pico-aio\n",
      "  Attempting uninstall: pyserial\n",
      "    Found existing installation: pyserial 3.5\n",
      "    Uninstalling pyserial-3.5:\n",
      "      Successfully uninstalled pyserial-3.5\n",
      "  Attempting uninstall: aioserial\n",
      "    Found existing installation: aioserial 1.3.1\n",
      "    Uninstalling aioserial-1.3.1:\n",
      "      Successfully uninstalled aioserial-1.3.1\n",
      "  Attempting uninstall: tmx-pico-aio\n",
      "    Found existing installation: tmx-pico-aio 1.3\n",
      "    Uninstalling tmx-pico-aio-1.3:\n",
      "      Successfully uninstalled tmx-pico-aio-1.3\n",
      "Successfully installed aioserial-1.3.1 pyserial-3.5 tmx-pico-aio-1.3\n",
      "Requirement already satisfied: nest_asyncio in c:\\users\\arendjanvanhil\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\\localcache\\local-packages\\python311\\site-packages (1.5.7)\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "!{sys.executable} -m pip install --upgrade --force-reinstall git+https://github.com/arendjan/tmx-pico-aio.git@sensors\n",
    "!{sys.executable} -m pip install nest_asyncio"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Create a board and connect your components:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-971' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-972' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-973' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-974' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-975' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-976' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-977' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-978' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-980' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-981' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-982' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-983' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-984' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-985' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-986' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-987' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-988' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-989' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-990' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-991' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-992' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-993' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-994' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-995' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-996' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-997' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-998' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-999' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1000' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1001' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1002' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1003' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1004' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1005' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1006' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1007' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1008' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1009' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1010' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1011' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1012' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1013' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1014' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1015' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1016' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1017' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1018' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1019' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1020' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1021' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1022' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1023' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1024' coro=<TmxPicoAio._analog_message() done, defined at C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py:1656> exception=TypeError(\"object NoneType can't be used in 'await' expression\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\\Lib\\asyncio\\tasks.py\", line 267, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\arendjanvanhil\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\tmx_pico_aio\\tmx_pico_aio.py\", line 1670, in _analog_message\n",
      "    await self.analog_callbacks[pin](message)\n",
      "TypeError: object NoneType can't be used in 'await' expression\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "TelemetrixRpiPicoAio:  Version 1.5\n",
      "\n",
      "Copyright (c) 2021 Alan Yorinks All Rights Reserved.\n",
      "\n",
      "Opening all potential serial ports...\n",
      "\tCOM13\n",
      "Retrieving pico ID...\n",
      "Pico Unique ID: [230, 97, 100, 8, 67, 88, 0, 0]\n",
      "Telemetrix4RPiPico Version Number: 1.2\n"
     ]
    }
   ],
   "source": [
    "import asyncio\n",
    "import sys\n",
    "import time\n",
    "from tmx_pico_aio import tmx_pico_aio\n",
    "import nest_asyncio\n",
    "import struct\n",
    "nest_asyncio.apply() # for jupyter notebook asyncio stuff\n",
    "\n",
    "loop = asyncio.get_event_loop()\n",
    "\n",
    "board = tmx_pico_aio.TmxPicoAio(loop=loop)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Add your callback, like printing or adding it to a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "async def the_callback(data):\n",
    "    print(data[2])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Add the sensor to the system"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "async def addSensor(board):\n",
    "    await asyncio.sleep(1)\n",
    "    adc = 0 # pin GP26\n",
    "    await board.set_pin_mode_analog_input(adc, differential=0, callback=the_callback)\n",
    "\n",
    "loop.run_until_complete(addSensor(board))\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Run for some time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "65\n",
      "66\n",
      "66\n",
      "66\n",
      "66\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "64\n",
      "66\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "67\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "66\n",
      "64\n",
      "66\n",
      "66\n",
      "64\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "66\n",
      "67\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "67\n",
      "66\n",
      "66\n",
      "64\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "64\n",
      "64\n",
      "66\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "64\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "66\n",
      "67\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "64\n",
      "66\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "67\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "65\n",
      "67\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "66\n",
      "66\n",
      "67\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "67\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "64\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "64\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "66\n",
      "66\n",
      "64\n",
      "66\n",
      "66\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "64\n",
      "65\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "64\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "66\n",
      "66\n",
      "64\n",
      "64\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "64\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "66\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "64\n",
      "66\n",
      "66\n",
      "65\n",
      "64\n",
      "65\n",
      "67\n",
      "66\n",
      "67\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "67\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "66\n",
      "66\n",
      "67\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "64\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "67\n",
      "66\n",
      "66\n",
      "65\n",
      "64\n",
      "66\n",
      "66\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "64\n",
      "64\n",
      "65\n",
      "65\n",
      "67\n",
      "66\n",
      "67\n",
      "67\n",
      "64\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "67\n",
      "65\n",
      "64\n",
      "65\n",
      "66\n",
      "66\n",
      "66\n",
      "66\n",
      "65\n",
      "67\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "66\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "67\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "66\n",
      "67\n",
      "67\n",
      "66\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "66\n",
      "66\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "68\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "66\n",
      "66\n",
      "64\n",
      "65\n",
      "67\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "67\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "64\n",
      "64\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "64\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "66\n",
      "65\n",
      "66\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "64\n",
      "66\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "66\n",
      "66\n",
      "66\n",
      "66\n",
      "64\n",
      "66\n",
      "68\n",
      "67\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "64\n",
      "66\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "67\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "67\n",
      "65\n",
      "66\n",
      "66\n",
      "63\n",
      "35\n",
      "53\n",
      "45\n",
      "58\n",
      "37\n",
      "58\n",
      "57\n",
      "67\n",
      "49\n",
      "63\n",
      "37\n",
      "50\n",
      "25\n",
      "49\n",
      "46\n",
      "53\n",
      "29\n",
      "49\n",
      "42\n",
      "52\n",
      "42\n",
      "54\n",
      "40\n",
      "58\n",
      "47\n",
      "45\n",
      "36\n",
      "49\n",
      "44\n",
      "53\n",
      "28\n",
      "52\n",
      "41\n",
      "60\n",
      "29\n",
      "52\n",
      "32\n",
      "46\n",
      "38\n",
      "41\n",
      "41\n",
      "53\n",
      "36\n",
      "57\n",
      "37\n",
      "60\n",
      "38\n",
      "68\n",
      "38\n",
      "30\n",
      "38\n",
      "48\n",
      "27\n",
      "53\n",
      "35\n",
      "57\n",
      "40\n",
      "52\n",
      "33\n",
      "49\n",
      "28\n",
      "46\n",
      "42\n",
      "57\n",
      "43\n",
      "44\n",
      "42\n",
      "52\n",
      "32\n",
      "53\n",
      "32\n",
      "53\n",
      "43\n",
      "48\n",
      "31\n",
      "45\n",
      "58\n",
      "66\n",
      "65\n",
      "67\n",
      "66\n",
      "66\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "64\n",
      "66\n",
      "65\n",
      "66\n",
      "66\n",
      "64\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "125\n",
      "67\n",
      "54\n",
      "60\n",
      "57\n",
      "58\n",
      "66\n",
      "53\n",
      "78\n",
      "78\n",
      "62\n",
      "64\n",
      "61\n",
      "59\n",
      "56\n",
      "81\n",
      "69\n",
      "67\n",
      "72\n",
      "51\n",
      "67\n",
      "62\n",
      "64\n",
      "56\n",
      "60\n",
      "69\n",
      "59\n",
      "68\n",
      "53\n",
      "65\n",
      "62\n",
      "39\n",
      "57\n",
      "72\n",
      "67\n",
      "53\n",
      "77\n",
      "73\n",
      "67\n",
      "66\n",
      "65\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "64\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "64\n",
      "65\n",
      "64\n",
      "61\n",
      "52\n",
      "68\n",
      "62\n",
      "60\n",
      "60\n",
      "62\n",
      "57\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "67\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "67\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "71\n",
      "64\n",
      "63\n",
      "61\n",
      "64\n",
      "67\n",
      "60\n",
      "52\n",
      "67\n",
      "62\n",
      "76\n",
      "47\n",
      "65\n",
      "67\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "48\n",
      "57\n",
      "53\n",
      "65\n",
      "63\n",
      "62\n",
      "56\n",
      "72\n",
      "59\n",
      "60\n",
      "57\n",
      "66\n",
      "67\n",
      "64\n",
      "66\n",
      "65\n",
      "64\n",
      "66\n",
      "65\n",
      "67\n",
      "64\n",
      "66\n",
      "65\n",
      "65\n",
      "20\n",
      "64\n",
      "52\n",
      "57\n",
      "53\n",
      "72\n",
      "60\n",
      "65\n",
      "60\n",
      "67\n",
      "68\n",
      "67\n",
      "65\n",
      "65\n",
      "66\n",
      "64\n",
      "65\n",
      "66\n",
      "66\n",
      "66\n",
      "64\n",
      "76\n",
      "53\n",
      "69\n",
      "64\n",
      "57\n",
      "57\n",
      "65\n",
      "66\n",
      "76\n",
      "66\n",
      "66\n",
      "66\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "67\n",
      "65\n",
      "68\n",
      "65\n",
      "66\n",
      "33\n",
      "76\n",
      "61\n",
      "81\n",
      "57\n",
      "82\n",
      "58\n",
      "62\n",
      "60\n",
      "67\n",
      "58\n",
      "69\n",
      "58\n",
      "75\n",
      "51\n",
      "70\n",
      "57\n",
      "64\n",
      "52\n",
      "70\n",
      "63\n",
      "80\n",
      "49\n",
      "79\n",
      "48\n",
      "80\n",
      "57\n",
      "67\n",
      "51\n",
      "64\n",
      "60\n",
      "70\n",
      "56\n",
      "67\n",
      "57\n",
      "76\n",
      "59\n",
      "69\n",
      "62\n",
      "77\n",
      "50\n",
      "73\n",
      "65\n",
      "70\n",
      "61\n",
      "64\n",
      "63\n",
      "76\n",
      "67\n",
      "77\n",
      "52\n",
      "81\n",
      "51\n",
      "73\n",
      "73\n",
      "74\n",
      "59\n",
      "70\n",
      "61\n",
      "72\n",
      "73\n",
      "73\n",
      "70\n",
      "64\n",
      "54\n",
      "61\n",
      "48\n",
      "70\n",
      "62\n",
      "75\n",
      "60\n",
      "59\n",
      "58\n",
      "70\n",
      "52\n",
      "71\n",
      "52\n",
      "73\n",
      "52\n",
      "60\n",
      "59\n",
      "73\n",
      "54\n",
      "61\n",
      "52\n",
      "62\n",
      "53\n",
      "46\n",
      "34\n",
      "48\n",
      "45\n",
      "64\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "66\n",
      "66\n",
      "64\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "67\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "67\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "64\n",
      "67\n",
      "66\n",
      "65\n",
      "64\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "65\n",
      "66\n",
      "66\n",
      "65\n",
      "65\n",
      "65\n",
      "67\n",
      "shutting down!\n",
      "64\n",
      "done\n"
     ]
    }
   ],
   "source": [
    "async def run_till_end(board):\n",
    "    # when to stop?\n",
    "    await asyncio.sleep(10)\n",
    "    await board.shutdown() # Otherwise next start will give you errors and you need to restart the kernel\n",
    "    await asyncio.sleep(1)\n",
    "    print(\"done\")\n",
    "\n",
    "loop.run_until_complete(run_till_end(board))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
